language: cpp
compiler: gcc
env:
  global:
    - secure: "T5etXz6ru3TSrrKuzyJ15w6uV4EquyJfPMVhSipMCbRgEZhjh5pAW4UrCluFXbJrg3dRqvnrNVJe1Oq3puPWy99p9Zwvi+WBJwWarxW3SOfeUAATHazFBbYxnu9OJc4I2H7WtmQbV2b/DhxQaBVkzabS5uOL3dyG8CxSxHcQ86o="
install:
  - chmod 0755 tools/travis/install.sh
  - tools/travis/install.sh
script:
  - make -j2
addons:
  coverity_scan:
    project:
      name: "TheJosh/chaotic-rage"
      description: "Build submitted via Travis CI"
    notification_email: josh.sickmate@gmail.com
    build_command_prepend: "chmod 0755 tools/travis/install.sh; tools/travis/install.sh"
    build_command: "make -j2"
    branch_pattern: coverity_scan
