language: cpp
compiler: gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libzzip-dev libconfuse-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev liblua5.1-0-dev libfreetype6-dev libguichan-dev zlib-bin freeglut3-dev
  - cd tools/linux
  - ./assimp.sh
  - ./bullet.sh
  - ./sdl2.sh
  - ./sdl2_image.sh
  - ./sdl2_mixer.sh
  - ./sdl2_net.sh
  - cd ../..
script:
  - make
  - ./chaoticrage --mod test --campaign pound --no-mouse-grab --audio=null --render=null
