language: cpp
compiler: gcc
env:
  - PLATFORM=linux
  - PLATFORM=android
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev libglu1-mesa-dev libglew-dev liblua5.1-0-dev libfreetype6-dev zlib-bin freeglut3-dev
  - if [ "$PLATFORM" == "linux" ]; then cd tools/linux; ./assimp.sh; ./bullet.sh; ./sdl2.sh; ./sdl2_image.sh; ./sdl2_mixer.sh; ./sdl2_net.sh; cd ../..; fi
  - if [ "$PLATFORM" == "android" ]; then cd tools/android; wget http://dl.google.com/android/ndk/android-ndk-r9b-linux-x86_64.tar.bz2; tar -xjf android-ndk-r9b-linux-x86_64.tar.bz2; cd ../..; fi
script:
  - if [ "$PLATFORM" == "linux" ]; then make; fi
  - if [ "$PLATFORM" == "android" ]; then cd tools/android; ./prepare.sh; android-ndk-r9b-linux-x86_64/ndk-build; fi
