language: cpp
compiler: gcc
env:
  - PLATFORM=linux
  - PLATFORM=android
install:
  - chmod 0755 tools/trvis/install.sh
  - tools/travis/install.sh
script:
  - chmod 0755 tools/trvis/script.sh
  - tools/travis/script.sh
