language: cpp
compiler: gcc
env:
  - PLATFORM=linux
install:
  - chmod 0755 tools/travis/install.sh
  - tools/travis/install.sh
script:
  - chmod 0755 tools/travis/script.sh
  - tools/travis/script.sh
